//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventmngmnt
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventtbl
    {
        public int Eventid { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Venue { get; set; }
        public string Program { get; set; }
        public string EventImage { get; set; }
    }
}
