//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventmngmnt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyEventsEntities1 : DbContext
    {
        public MyEventsEntities1()
            : base("name=MyEventsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RegisterTbl> RegisterTbls { get; set; }
        public virtual DbSet<feedbacktbl> feedbacktbls { get; set; }
        public virtual DbSet<eventtbl> eventtbls { get; set; }
    }
}
